<a href="https://colab.research.google.com/github/Rectifiant/StatsHomework/blob/main/JoelMedrano_2023_lab_3new.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [67]:
for i in range(100): #Printed numbers 0-99
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [68]:
for i in range(5,8):#printed numbers 5-7
    print(i)

5
6
7


In [69]:
for i in range(3): #printed numbers 0-2
    print( "Test Number: " , i )

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [70]:
def square(x):
    return x**2 #defined square and any number for x will be squared

In [71]:
square(5) #5 squared 

25

In [72]:
square(square(2)) # 2 squared is 4. and 4 squared is 16

16

In [73]:
square(square(square(2)))#2 squared is 4. 4 squared is 16. 16 squared is 256


256

In [74]:
square(123456) #squaring 123456

15241383936

In [75]:
square(square(5)) #5 squared us 25. 25 squared is 625

625

In [76]:
def add_two(x): ##defined add_two and whatever x is , it will add 2
    return x+2

In [77]:
add_two(5) #5 + 2

7

In [78]:
square(add_two(5))# 5 + 2 is 7. 7 squared is 49

49

### Logical Branching

In [28]:
choice = "apple" # choice now equals apples 

In [29]:
if choice == "apple": # declaring an if-then statement. 

    print("You choose apples.") #Printing "uyou choose apples"

else:
    
    print("You did not choose apples.") # Printing "you did not choose apples"

You choose apples.


In [30]:
choice = "orange" # choice will now equal orange

In [31]:
if choice == "apple": #declare an if then statement .

    print("You choose apples.") # it will not print this because it is a false statement.

else:
    
    print("You did not choose apples.") # it will print this because it is a true statement

You did not choose apples.


In [32]:
choice = "apple" #choice will not equal apples

In [33]:
if choice == "apple": # if than statement 

    print("You choose apples.")
    print("Thank you, shop again!") # will print this if you choose apples
    print(2**123)

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!") #if you chooose oranges this will display

else:
    
    print("You did not choose apples or oranges.") # if neither this will print
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [34]:
choice = input("Please enter your choice (i.e. apple): ") # will ask you to enter your choice.

Please enter your choice (i.e. apple): 


In [35]:
choice 

''

In [36]:
if choice == "apple": # If apple it wll print this

    print("You choose apples.")

elif choice == "oranges": # if orange it will print you choose ornages.

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.") #if neither it will print this .

You did not choose apples or oranges.


#### Coins

In [79]:
np.random.random() #will print a random number 

NameError: ignored

In [80]:
np.random.random() > 0.5 #a random number wil be greater than 5

NameError: ignored

In [81]:
def flip_coin(): #flip_coin will be defined 
    if np.random.random() > 0.5:n # if then statement, more than . 5 it will print heads. less will print a tail
        print("Heads") 
    else:
        print("Tails")

IndentationError: ignored

In [82]:
flip_coin() 

NameError: ignored

### Graphics Output

In [83]:
from IPython.core.display import display, HTML

In [84]:
display(HTML('<h1>Hello, world!</h1>')) #  will display hello worlds

In [85]:
def coin(): #define coin 
  return np.random.randint(2)  #will display random numbers 

In [86]:
coin() 

NameError: ignored

In [87]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">')) #this is the image if the head on a quarter

In [88]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg' # this is the url for heads and tails 

In [89]:
def show_img(img): # define show_img 
  display(HTML('<img src=' + img + '>')) 

In [90]:
show_img(heads) #show the image of heads

In [91]:
show_img(tails) #this is will show tails 

In [92]:
def flip_coin(): # define flip_coin 

    if coin(): # If head it will display, if not it will display tails
        show_img(heads) 
    else:
        show_img(tails)

In [93]:
flip_coin()

NameError: ignored

In [94]:
for i in range(5): # i wil be between 1-4
    flip_coin()

NameError: ignored

In [95]:
#@title Coin Flip
 
if coin():

  show_img(heads) #if then statement. will be heads if not tails

else:

  show_img(tails)

NameError: ignored

### Cards

In [96]:
def shuffle(x):
    for i in range(len(x)-1,0,-1): # i do not know 
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [97]:
a = np.arange(52) # creates an array 0-51

NameError: ignored

In [98]:
shuffle(a) #  shuffle the letter a 

NameError: ignored

In [99]:
np.random.permutation(52) # will randomize 

NameError: ignored

### Speed Test

In [100]:
%%timeit
shuffle(a)  #use to time a particular piece if code. in this case it will time how long it takes to shuffle 

NameError: ignored

In [101]:
%%timeit
np.random.permutation(52) #will time how long it takes to gather random permutations 

NameError: ignored

In [102]:
import numpy as np #will use np as numpy

In [103]:
np.random.permutation(52) #generated random permutations

array([34, 22, 40,  6, 27, 25, 49, 41, 36, 13, 33, 51,  5, 21, 11, 15,  9,
       43, 48,  7, 39, 26, 24, 12, 35, 29,  1, 50, 23,  4, 10, 38, 28, 32,
       47, 44, 37,  8,  0,  2, 19, 20, 31,  3, 46, 18, 16, 30, 45, 42, 17,
       14])

In [104]:
cards = np.random.permutation(52) #the random 52 permutations will be identified as cards

In [105]:
cards # will print cards

array([38, 44, 23,  0, 34,  1,  9, 30, 32,  2, 51, 45, 41, 12, 18, 36,  4,
        5, 31, 47, 19, 49, 10, 29, 50, 43,  7, 46, 11, 17, 21, 26,  6, 33,
       20, 16, 39, 14, 37, 48, 28,  3, 13, 42, 25, 27, 24, 15,  8, 22, 35,
       40])

In [106]:
cards[0] #card 0 will be 21

38

In [107]:
cards[1] #card one will be  2

44

In [108]:
cards[2] #card 2 will be number 42 

23

In [109]:
 #an uploaded image of a deck of playing cards

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [110]:
np.arange(52).reshape(4,13) # there is an array of 53 numbers and will reshappe the array 4-13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [111]:
np.arange(52).reshape(4,13)%13 #change the order of the numbers and %13 is the remainder

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [112]:
np.arange(52).reshape(4,13)//13 # change the order and divided by 13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [113]:
suits = ['Clubs','Spades','Hearts','Diamonds'] #suits are one of the 4
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King'] #names can be one of the 15 options 

In [114]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [115]:
card_name(0) #card name 0 is "ace of clubs"

'Ace of Clubs'

In [116]:
card_name(51) #card name 51 is "king of diamonds"

'King of Diamonds'

In [117]:
cards = np.random.permutation(52) # cards will equal random permutations 

In [118]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1]) # giving the card titles a dedicated number 
last_card_in_deck   = card_name(cards[-1])

In [119]:
top_of_deck, second_card_in_deck, last_card_in_deck #will print the 3

('Two of Hearts', 'Seven of Clubs', 'Four of Spades')

In [120]:
for i in range(5):
    print(card_name(cards[i])) # i in a range 5 will be one of the 5 choices

Two of Hearts
Seven of Clubs
Ace of Clubs
Ace of Diamonds
Jack of Hearts


In [121]:
for i in range(15):
    print(card_name(cards[i]))n # i will print one of the 15 cards

Two of Hearts
Seven of Clubs
Ace of Clubs
Ace of Diamonds
Jack of Hearts
Seven of Hearts
Three of Diamonds
Four of Clubs
Eight of Hearts
Queen of Spades
Nine of Diamonds
Ten of Clubs
Six of Diamonds
Nine of Spades
Eight of Clubs


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [122]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/" #giving the url of heads and tails
card_url_tail = ".png"

In [123]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k'] # suits and card are given set values

In [137]:
i = np.random.randint(4) #i will be up to 4 numbers and j will be up to 13 numbers
j = np.random.randint(13)

In [150]:
i,j #i an j will be printed

(0, 8)

In [152]:
suit[i] # a suit will print for i

'k'

In [127]:
card[j] # a card will print for j

'8'

In [128]:
from IPython.core.display import display, HTML

In [129]:
def show_img(img):
  display(HTML('<img src=' + img + '>')) #will display an image 

In [130]:
img = card_url_head + suit[i] + card[j] + card_url_tail # img will equal all of these

In [131]:
show_img(img) #will show an image 

In [132]:
def card_image(card_number):n # defined card image
    
    i = card_number//13 #
    j = card_number%13

    return suit[i]+card[j]

In [153]:
card_image(3) #card image foro card 3

'k4'

In [134]:
img = card_url_head + card_image(3) + card_url_tail # img will display a card

In [135]:
show_img(img) # display image

In [136]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail #for i in range of 52 cars
    show_img(img)