<a href="https://colab.research.google.com/github/Rectifiant/StatsHomework/blob/main/JoelMedrano_2023_lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [48]:
for i in range(100): #Printed numbers 0-99
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [49]:
for i in range(5,8):#printed numbers 5-7
    print(i)

5
6
7


In [50]:
for i in range(3): #printed numbers 0-2
    print( "Test Number: " , i )

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [5]:
def square(x):
    return x**2 #defined square and any number for x will be squared

In [6]:
square(5) #5 squared 

25

In [7]:
square(square(2)) # 2 squared is 4. and 4 squared is 16

16

In [8]:
square(square(square(2)))#2 squared is 4. 4 squared is 16. 16 squared is 256


256

In [9]:
square(123456) #squaring 123456

15241383936

In [10]:
square(square(5)) #5 squared us 25. 25 squared is 625

625

In [11]:
def add_two(x): ##defined add_two and whatever x is , it will add 2
    return x+2

In [12]:
add_two(5) #5 + 2

7

In [13]:
square(add_two(5))# 5 + 2 is 7. 7 squared is 49

49

### Logical Branching

In [2]:
choice = "apple" # choice now equals apples 

In [3]:
if choice == "apple": # declaring an if-then statement. 

    print("You choose apples.") #Printing "uyou choose apples"

else:
    
    print("You did not choose apples.") # Printing "you did not choose apples"

You choose apples.


In [4]:
choice = "orange" # choice will now equal orange

In [5]:
if choice == "apple": #declare an if then statement .

    print("You choose apples.") # it will not print this because it is a false statement.

else:
    
    print("You did not choose apples.") # it will print this because it is a true statement

You did not choose apples.


In [6]:
choice = "apple" #choice will not equal apples

In [7]:
if choice == "apple": # if than statement 

    print("You choose apples.")
    print("Thank you, shop again!") # will print this if you choose apples
    print(2**123)

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!") #if you chooose oranges this will display

else:
    
    print("You did not choose apples or oranges.") # if neither this will print
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [8]:
choice = input("Please enter your choice (i.e. apple): ") # will ask you to enter your choice.

Please enter your choice (i.e. apple): 


In [9]:
choice 

''

In [10]:
if choice == "apple": # If apple it wll print this

    print("You choose apples.")

elif choice == "oranges": # if orange it will print you choose ornages.

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.") #if neither it will print this .

You did not choose apples or oranges.


#### Coins

In [11]:
np.random.random() #will print a random number 

NameError: ignored

In [13]:
np.random.random() > 0.5 #a random number wil be greater than 5

NameError: ignored

In [14]:
def flip_coin(): #flip_coin will be defined 
    if np.random.random() > 0.5:n # if then statement, more than . 5 it will print heads. less will print a tail
        print("Heads") 
    else:
        print("Tails")

IndentationError: ignored

In [12]:
flip_coin() 

NameError: ignored

### Graphics Output

In [27]:
from IPython.core.display import display, HTML

In [28]:
display(HTML('<h1>Hello, world!</h1>')) #  will display hello worlds

In [15]:
def coin(): #define coin 
  return np.random.randint(2)  #will display random numbers 

In [16]:
coin() 

NameError: ignored

In [31]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">')) #this is the image if the head on a quarter

In [32]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg' # this is the url for heads and tails 

In [33]:
def show_img(img): # define show_img 
  display(HTML('<img src=' + img + '>')) 

In [34]:
show_img(heads) #show the image of heads

In [35]:
show_img(tails) #this is will show tails 

In [36]:
def flip_coin(): # define flip_coin 

    if coin(): # If head it will display, if not it will display tails
        show_img(heads) 
    else:
        show_img(tails)

In [37]:
flip_coin()

NameError: ignored

In [38]:
for i in range(5): # i wil be between 1-4
    flip_coin()

NameError: ignored

In [39]:
#@title Coin Flip
 
if coin():

  show_img(heads)

else:

  show_img(tails)

NameError: ignored

### Cards

In [40]:
def shuffle(x):
    for i in range(len(x)-1,0,-1): # idk 
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [41]:
a = np.arange(52) # creats an array 0-51

NameError: ignored

In [42]:
shuffle(a) #  shuffle the letter a 

NameError: ignored

In [43]:
np.random.permutation(52) # will randomize 

NameError: ignored

### Speed Test

In [ ]:
%%timeit
shuffle(a)

In [ ]:
%%timeit
np.random.permutation(52)

In [ ]:
import numpy as np

In [ ]:
np.random.permutation(52)

array([51, 40, 39,  2, 19, 24, 12,  7, 14, 28,  8, 21, 18, 49, 47, 27,  1,
       44, 10, 16, 42,  3, 43, 31, 46, 29, 38,  4, 23,  5, 50, 35, 41, 36,
       11, 13, 34, 15, 32, 26, 45, 20, 48, 30,  9, 17, 33,  0, 22, 25,  6,
       37])

In [ ]:
cards = np.random.permutation(52)

In [ ]:
cards

array([32,  0, 51, 29, 27, 15, 39, 45, 42, 12, 30, 28, 44, 34, 33, 16, 49,
       47,  6, 22, 40, 24, 10, 21, 11, 23, 41, 48,  5, 36, 13, 46, 31, 17,
        7, 14,  1, 26,  2, 43, 25,  4, 35, 18,  8, 37, 50,  9,  3, 38, 20,
       19])

In [ ]:
cards[0]

32

In [ ]:
cards[1]

0

In [ ]:
cards[2]

51

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [ ]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [ ]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [ ]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [ ]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [ ]:
card_name(0)

'Ace of Clubs'

In [ ]:
card_name(51)

'King of Diamonds'

In [ ]:
cards = np.random.permutation(52)

In [ ]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [ ]:
top_of_deck, second_card_in_deck, last_card_in_deck

('Three of Hearts', 'Nine of Diamonds', 'Ten of Hearts')

In [ ]:
for i in range(5):
    print(card_name(cards[i]))

Four of Spades
Six of Diamonds
Ace of Diamonds
Eight of Clubs
Three of Diamonds


In [ ]:
for i in range(15):
    print(card_name(cards[i]))

Seven of Hearts
Ace of Clubs
King of Diamonds
Four of Hearts
Two of Hearts
Three of Spades
Ace of Diamonds
Seven of Diamonds
Four of Diamonds
King of Clubs
Five of Hearts
Three of Hearts
Six of Diamonds
Nine of Hearts
Eight of Hearts


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [ ]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [ ]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [ ]:
i = np.random.randint(4)
j = np.random.randint(13)

In [ ]:
i,j

(0, 11)

In [ ]:
suit[i]

'k'

In [ ]:
card[j]

'q'

In [ ]:
from IPython.core.display import display, HTML

In [ ]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [ ]:
img = card_url_head + suit[i] + card[j] + card_url_tail

In [ ]:
show_img(img)

In [ ]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [ ]:
card_image(3)

'k4'

In [ ]:
img = card_url_head + card_image(3) + card_url_tail

In [ ]:
show_img(img)

In [ ]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)