<a href="https://colab.research.google.com/github/Rectifiant/StatsHomework/blob/main/JoelMedrano_2023_lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [25]:
for i in range(100): #Printed numbers 0-99
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [26]:
for i in range(5,8):#printed numbers 5-7
    print(i)

5
6
7


In [27]:
for i in range(3): #printed numbers 0-2
    print( "Test Number: " , i )

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [28]:
def square(x):
    return x**2 #defined square and any number for x will be squared

In [29]:
square(5) #5 squared 

25

In [30]:
square(square(2)) # 2 squared is 4. and 4 squared is 16

16

In [31]:
square(square(square(2)))#2 squared is 4. 4 squared is 16. 16 squared is 256


256

In [32]:
square(123456) #squaring 123456

15241383936

In [33]:
square(square(5)) #5 squared us 25. 25 squared is 625

625

In [34]:
def add_two(x): ##defined add_two and whatever x is , it will add 2
    return x+2

In [35]:
add_two(5) #5 + 2

7

In [36]:
square(add_two(5))# 5 + 2 is 7. 7 squared is 49

49

### Logical Branching

In [37]:
choice = "apple" # choice now equals apples 

In [38]:
if choice == "apple": # declaring an if-then statement. 

    print("You choose apples.") #Printing "uyou choose apples"

else:
    
    print("You did not choose apples.") # Printing "you did not choose apples"

You choose apples.


In [39]:
choice = "orange" # choice will now equal orange

In [40]:
if choice == "apple": #declare an if then statement .

    print("You choose apples.") # it will not print this because it is a false statement.

else:
    
    print("You did not choose apples.") # it will print this because it is a true statement

You did not choose apples.


In [41]:
choice = "apple" #choice will not equal apples

In [42]:
if choice == "apple": # if than statement 

    print("You choose apples.")
    print("Thank you, shop again!") # will print this if you choose apples
    print(2**123)

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!") #if you chooose oranges this will display

else:
    
    print("You did not choose apples or oranges.") # if neither this will print
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [43]:
choice = input("Please enter your choice (i.e. apple): ") # will ask you to enter your choice.

Please enter your choice (i.e. apple): 


In [44]:
choice 

''

In [45]:
if choice == "apple": # If apple it wll print this

    print("You choose apples.")

elif choice == "oranges": # if orange it will print you choose ornages.

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.") #if neither it will print this .

You did not choose apples or oranges.


#### Coins

In [46]:
np.random.random() #will print a random number 

NameError: ignored

In [47]:
np.random.random() > 0.5 #a random number wil be greater than 5

NameError: ignored

In [48]:
def flip_coin(): #flip_coin will be defined 
    if np.random.random() > 0.5:n # if then statement, more than . 5 it will print heads. less will print a tail
        print("Heads") 
    else:
        print("Tails")

IndentationError: ignored

In [49]:
flip_coin() 

NameError: ignored

### Graphics Output

In [50]:
from IPython.core.display import display, HTML

In [51]:
display(HTML('<h1>Hello, world!</h1>')) #  will display hello worlds

In [52]:
def coin(): #define coin 
  return np.random.randint(2)  #will display random numbers 

In [53]:
coin() 

NameError: ignored

In [54]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">')) #this is the image if the head on a quarter

In [55]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg' # this is the url for heads and tails 

In [56]:
def show_img(img): # define show_img 
  display(HTML('<img src=' + img + '>')) 

In [57]:
show_img(heads) #show the image of heads

In [58]:
show_img(tails) #this is will show tails 

In [59]:
def flip_coin(): # define flip_coin 

    if coin(): # If head it will display, if not it will display tails
        show_img(heads) 
    else:
        show_img(tails)

In [77]:
flip_coin()

In [76]:
for i in range(5): # i wil be between 1-4
    flip_coin()

In [75]:
#@title Coin Flip
 
if coin():

  show_img(heads) #if then statement. will be heads if not tails

else:

  show_img(tails)

### Cards

In [84]:
def shuffle(x):
    for i in range(len(x)-1,0,-1): # i do not know 
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [78]:
a = np.arange(52) # creates an array 0-51

In [79]:
shuffle(a) #  shuffle the letter a 

array([ 1, 25, 24, 46,  5, 35, 30, 47, 26,  4, 44, 37, 15, 39,  3, 32, 33,
       27, 34, 49, 28, 11, 22, 20,  2, 40, 45, 38, 19,  7, 23, 16, 41, 18,
       21, 12, 14,  9, 31, 48, 50,  6, 51, 36, 10, 13, 17,  8, 29,  0, 43,
       42])

In [80]:
np.random.permutation(52) # will randomize 

array([13, 34, 10, 47, 15,  6, 27,  1, 39, 33, 40, 28, 19,  0, 16, 26, 25,
        9, 12,  2, 49, 43,  5, 11, 21, 32, 31, 42, 51, 22,  4, 35, 41, 17,
        8, 50, 20, 44, 38, 30, 24,  3, 45, 29, 36, 48, 14, 18, 37,  7, 23,
       46])

### Speed Test

In [87]:
%%timeit
shuffle(a)  #use to time a particular piece if code. in this case it will time how long it takes to shuffle 

171 µs ± 9.53 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [88]:
%%timeit
np.random.permutation(52) #will time how long it takes to gather random permutations 

3.32 µs ± 189 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [89]:
import numpy as np #will use np as numpy

In [90]:
np.random.permutation(52) #generated random permutations

array([34, 39,  9, 36, 16, 33, 45, 40, 42,  0, 30, 32, 25, 43,  8, 41, 51,
       22, 27, 21,  2,  7, 12, 31, 49,  3, 29, 26, 13,  5, 23, 44, 20,  1,
       47, 10, 38, 14, 28, 19, 50, 24, 18, 15, 37,  4, 48, 46, 35,  6, 11,
       17])

In [91]:
cards = np.random.permutation(52) #the random 52 permutations will be identified as cards

In [92]:
cards # will print cards

array([40, 46, 26, 10, 36, 16, 47,  9, 14, 20, 19, 32,  8,  7, 34, 27,  0,
       42, 35, 33, 28, 43, 48, 45, 15, 25,  5, 39, 41, 17, 49, 21, 51, 22,
       44, 24, 37,  2,  3, 12,  1,  4, 29,  6, 13, 38, 30, 18, 23, 50, 11,
       31])

In [93]:
cards[0] #card 0 will be 21

40

In [94]:
cards[1] #card one will be  2

46

In [95]:
cards[2] #card 2 will be number 42 

26

In [98]:
 #an uploaded image of a deck of playing cards

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [96]:
np.arange(52).reshape(4,13) # there is an array of 53 numbers and will reshappe the array 4-13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [103]:
np.arange(52).reshape(4,13)%13 #change the order of the numbers and %13 is the remainder

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [98]:
np.arange(52).reshape(4,13)//13 # change the order and divided by 13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [ ]:
suits = ['Clubs','Spades','Hearts','Diamonds'] #suits are one of the 4
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King'] #names can be one of the 15 options 

In [ ]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [ ]:
card_name(0) #card name 0 is "ace of clubs"

'Ace of Clubs'

In [ ]:
card_name(51)

'King of Diamonds'

In [ ]:
cards = np.random.permutation(52)

In [ ]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [ ]:
top_of_deck, second_card_in_deck, last_card_in_deck

('Three of Hearts', 'Nine of Diamonds', 'Ten of Hearts')

In [ ]:
for i in range(5):
    print(card_name(cards[i]))

Four of Spades
Six of Diamonds
Ace of Diamonds
Eight of Clubs
Three of Diamonds


In [ ]:
for i in range(15):
    print(card_name(cards[i]))

Seven of Hearts
Ace of Clubs
King of Diamonds
Four of Hearts
Two of Hearts
Three of Spades
Ace of Diamonds
Seven of Diamonds
Four of Diamonds
King of Clubs
Five of Hearts
Three of Hearts
Six of Diamonds
Nine of Hearts
Eight of Hearts


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [ ]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [ ]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [ ]:
i = np.random.randint(4)
j = np.random.randint(13)

In [ ]:
i,j

(0, 11)

In [ ]:
suit[i]

'k'

In [ ]:
card[j]

'q'

In [ ]:
from IPython.core.display import display, HTML

In [ ]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [ ]:
img = card_url_head + suit[i] + card[j] + card_url_tail

In [ ]:
show_img(img)

In [ ]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [ ]:
card_image(3)

'k4'

In [ ]:
img = card_url_head + card_image(3) + card_url_tail

In [ ]:
show_img(img)

In [83]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)

NameError: ignored